# Generated by Django 3.1.13 on 2021-09-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('primary_phone_number', models.CharField(max_length=10)),
                ('alternate_phone_number', models.CharField(max_length=10)),
                ('item_category', models.CharField(choices=[('Mobile Phone', 'Mobile Phones'), ('Home, Furniture & Appliances', 'Home, Furniture & Appliances'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=200)),
                ('purchase_item', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[('Loan', 'Loan'), ('Cash', 'Cash')], max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'New Orders',
            },
        ),
    ]
